### ISSUE TITLE
very thanks.

### ISSUE THREAD

**Issue by vahidalvandi** [masoudjahromi/Laravel-Cassandra#1]
please update this..

why have this error

```Use of undefined constant SO_RCVTIMEO - assumed 'SO_RCVTIMEO'```

**Comment by masoudjahromi** [comment]
@vahidalvandi 

Check this extension and make sure it is activated.

php_sockets.dll

https://stackoverflow.com/a/1361937/3881260

**Comment by vahidalvandi** [comment]
thanks. i found another package Dear shahin created it . 
please see this a help to develop it

https://github.com/ShahinSorkh/laravel-cassandra

**Comment by masoudjahromi** [comment]
This is very good package. You can using query builder.

Good luck ;)

**Comment by vahidalvandi** [comment]
yes ,
